image: 33578522838/clpq-environment:latest

stages:
  
  - basicLogic
  - validate1
  - ValidationStep
  - validate2
  - release 

before_script:
  - apt-get update && apt-get install -y zip curl jq

###################
# Stage 1: Always-run basicLogic
###################
basicTests:
  stage: basicLogic
  tags: [juno]
  script:
    - ./tests/RUN_PROLOG_test.sh clp clp
    - ./tests/RUN_SETLOG_test.sh abz18 abz
  artifacts:
    paths:
      - tests/logs/log_*
    expire_in: 1 week

###################
# Stage 2: Validate after basicLogic
###################
validate_after_basic:
  stage: validate1
  tags: [juno]
  needs:
    - basicTests
  script:
    - ./tests/validate.sh
  artifacts:
    paths:
      - tests/logs/log_*
    expire_in: 1 week

###################
# Stage 3: ValidationStep (Manual)
###################
cardTests:
  stage: ValidationStep
  when: manual
  allow_failure: true
  script:
    - ./tests/RUN_SETLOG_test.sh card nfs
  artifacts:
    paths:
      - tests/logs/log_*
    expire_in: 1 week

intervalsTests:
  stage: ValidationStep
  when: manual
  allow_failure: true
  script:
    - ./tests/RUN_SETLOG_test.sh intervals int
  artifacts:
    paths:
      - tests/logs/log_*
    expire_in: 1 week

###################
# Stage 4: Validate after ValidationStep
###################
validate_after_medium:
  stage: validate2
  needs:
    - intervalsTests
    - cardTests
  script:
    - ./tests/validate.sh
  artifacts:
    paths:
      - tests/logs/log_*
    expire_in: 1 week

###################
# Stage 7: Push release to github
###################
push_release:
  stage: release
  when: manual
  variables:
    VERSION: ""      # <-- Version number
  # tags: [juno]
  script:
    
    - '[ -n "$VERSION" ] || { echo "Set VERSION in the form."; exit 1; }'

    - apt-get install -y git
    - apt-get update && apt-get install -y rsync
    - DATE_SUFFIX=$(date +'_%Y-%m-%d-%H%M%S')

    - git config --global user.email "${GITHUB_MAIL}"
    - git config --global user.name "${GITHUB_USER}"

    - git clone "https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/Yaraslaw/linprog.git" TMP-github_repo

    - rsync -av --delete --exclude 'TMP-github_repo/' --exclude '**/.git/**' --exclude '/tests/test_cases/test_abz18/**' ./ ./TMP-github_repo/
    - rm -rf TMP-github_repo/tests/test_cases/test_abz18 # delete abz18 if it was there before

    - ls -la 
    - ./helpers/packaging/create_package.sh
    - ls -la 
    - mv package TMP-github_repo/
    - cd TMP-github_repo
    - ls -la 
    - git add -A
    - git add -f package/ # add package only for github
    - git commit -m "Release ${VERSION}" || echo "No changes to commit"

    - git remote add gitlab "https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/uniluxembourg/fstm/dcs/veridex/setlog/clpq.git"


    - git push origin main

    - git tag -a "v${VERSION}" -m "Release ${VERSION}"
    - git push origin "v${VERSION}"
    - git push -o ci.skip gitlab "refs/tags/v${VERSION}:refs/tags/v${VERSION}"
    - git remote -v
    - git status -s
